# Generated by Django 3.1.1 on 2020-10-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201029_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='challenge_id',
            new_name='challenge',
        ),
    ]
