# Generated by Django 3.1.1 on 2020-09-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mentor_mentorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorias',
            old_name='mentorias_id',
            new_name='mentor_id',
        ),
        migrations.AddField(
            model_name='mentor',
            name='challenge_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.challenge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorias',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='challenge_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.challenge'),
        ),
    ]
