# Generated by Django 3.1.1 on 2020-09-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200925_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentorias',
            new_name='Mentoring',
        ),
    ]
