# Generated by Django 3.1.1 on 2020-10-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201029_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.challenge'),
        ),
    ]
