# Generated by Django 3.1.1 on 2020-09-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200925_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='used_id',
            new_name='user_id',
        ),
    ]
