# Generated by Django 3.1.1 on 2020-11-01 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201029_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoring',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
