# Generated by Django 3.1.1 on 2020-09-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200925_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='challenge_id',
            new_name='challenge',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='user_id',
            new_name='user',
        ),
    ]
