# Generated by Django 3.1.1 on 2020-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201101_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='link_project',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
