# Generated by Django 3.1.1 on 2020-09-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200925_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoring',
            old_name='mentor_id',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='mentoring',
            old_name='team_id',
            new_name='team',
        ),
    ]
