# Generated by Django 3.1.1 on 2020-11-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_link_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='noteJudged',
            new_name='noteJudger',
        ),
    ]
