# Generated by Django 3.1.1 on 2020-09-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200925_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='challenge_id',
            new_name='challenge',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='user_id',
            new_name='user',
        ),
    ]
